language: node_js
node_js:
  - '10'
  - '8'
cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
notifications:
  email: false
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
